[FileDialog]
history=file:///home/hermit/data/sync/Password Manager, file:///home/hermit/doc/\xc3\xa8\xc2\x80\xc2\x83\xc3\xa7\xc2\xa0\xc2\x94\xc3\xa6\xc2\x95\xc2\xb0\xc3\xa5\xc2\xad\xc2\xa6, file:///home/hermit/ebook/out_ebook, file:///home/hermit/doc/qqfile, file:///home/hermit/data/doc, file:///home/hermit/doc
lastVisited=file:///home/hermit/doc
qtVersion=5.12.12
shortcuts=file:, file:///home/hermit
sidebarWidth=164
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2 \0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1O\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x61\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
