[FileDialog]
history=file:///home/hermit/doc/office, file:///home/hermit/doc/office/\xc3\xa5\xc2\xa4\xc2\xa7\xc3\xa5\xc2\xad\xc2\xa6\xc3\xa7\xc2\x94\xc2\x9f\xc3\xa5\xc2\xb0\xc2\xb1\xc3\xa4\xc2\xb8\xc2\x9a\xc3\xa6\xc2\x8c\xc2\x87\xc3\xa5\xc2\xaf\xc2\xbc, file:///home/hermit/ebook/out_ebook, file:///home/hermit/dls, file:///home/hermit/data/sync/ebook/out_ebook
lastVisited=file:///home/hermit/dls
qtVersion=5.15.14
shortcuts=file:, file:///home/hermit
sidebarWidth=164
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2k\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1?\0\0\0\x1\0\0\0\0\0\0\0\x93\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x61\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
